# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160923_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='introduction',
            new_name='summary',
        ),
    ]
